application: vatsal-gsoc-cloud-cv
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
  http_headers: {'Access-Control-Allow-Origin':'*'}
- url: /.*
  script: mainapp.app
  secure: always

libraries:
- name: webapp2
  version: "2.5.2"

